import React, { useState, useEffect } from 'react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { 
  FileText, 
  Download, 
  FileJson, 
  Calendar, 
  ShieldAlert, 
  Activity, 
  CheckCircle2,
  Loader2,
  Settings,
  History
} from 'lucide-react';
import { AdminRole, SystemMetrics } from '../types';

interface ReportGenerationEngineProps {
  currentRole: AdminRole;
  metrics: SystemMetrics | null;
}

type ReportType = 'PERFORMANCE' | 'SECURITY_AUDIT' | 'COMPLIANCE_SNAPSHOT';
type ExportFormat = 'PDF' | 'JSON';
type DateRange = '24H' | '7D' | '30D';

interface GeneratedReport {
  id: string;
  name: string;
  type: ReportType;
  format: ExportFormat;
  timestamp: string;
  size: string;
}

export const ReportGenerationEngine: React.FC<ReportGenerationEngineProps> = ({
  currentRole,
  metrics,
}) => {
  const [reportType, setReportType] = useState<ReportType>('PERFORMANCE');
  const [dateRange, setDateRange] = useState<DateRange>('7D');
  const [exportFormat, setExportFormat] = useState<ExportFormat>('PDF');
  const [isGenerating, setIsGenerating] = useState(false);
  const [recentReports, setRecentReports] = useState<GeneratedReport[]>([
    {
      id: 'REP-001',
      name: 'Weekly Security Audit',
      type: 'SECURITY_AUDIT',
      format: 'PDF',
      timestamp: new Date(Date.now() - 86400000).toISOString(),
      size: '1.2 MB'
    },
    {
      id: 'REP-002',
      name: 'Throughput Metrics',
      type: 'PERFORMANCE',
      format: 'JSON',
      timestamp: new Date(Date.now() - 172800000).toISOString(),
      size: '45 KB'
    }
  ]);

  const generateMockData = () => {
    return {
      metadata: {
        generatedAt: new Date().toISOString(),
        generatedBy: currentRole,
        reportType,
        dateRange,
      },
      performance: {
        avgLatencyMs: metrics?.currentLatencyMs || 45,
        cpuUsagePct: 32,
        memoryUsageMb: metrics?.memoryUsageMB || 1024,
        activeConnections: metrics?.activeWsConnections || 15,
        totalItemsMigrated: 145892,
        failedItems: 23,
      },
      security: {
        failedLoginAttempts: 2,
        unauthorizedAccessBlocks: 5,
        encryptionStatus: 'AES-256-GCM / TLS 1.3 Active',
        activeTokens: 4,
      }
    };
  };

  const handleGenerateReport = async () => {
    setIsGenerating(true);
    
    // Simulate generation delay
    await new Promise(resolve => setTimeout(resolve, 1500));

    const data = generateMockData();
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const fileName = `Migration_Report_${reportType}_${timestamp}`;

    if (exportFormat === 'JSON') {
      const jsonString = JSON.stringify(data, null, 2);
      const blob = new Blob([jsonString], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${fileName}.json`;
      link.click();
      URL.revokeObjectURL(url);
    } else {
      const doc = new jsPDF();
      
      // Header
      doc.setFontSize(20);
      doc.setTextColor(15, 23, 42); // slate-900
      doc.text('M365 Migration Engine', 14, 22);
      
      doc.setFontSize(12);
      doc.setTextColor(100, 116, 139); // slate-500
      doc.text(`Compliance & Metrics Report: ${reportType.replace('_', ' ')}`, 14, 32);
      
      // Metadata section
      doc.setFontSize(10);
      doc.text(`Generated By: ${currentRole}`, 14, 45);
      doc.text(`Date Range: Last ${dateRange}`, 14, 52);
      doc.text(`Timestamp: ${new Date().toLocaleString()}`, 14, 59);

      // Add Tables based on report type
      if (reportType === 'PERFORMANCE' || reportType === 'COMPLIANCE_SNAPSHOT') {
        doc.setFontSize(14);
        doc.setTextColor(15, 23, 42);
        doc.text('Performance Metrics', 14, 75);
        
        autoTable(doc, {
          startY: 80,
          head: [['Metric', 'Value']],
          body: [
            ['Average Latency (ms)', `${data.performance.avgLatencyMs}`],
            ['CPU Usage', `${data.performance.cpuUsagePct}%`],
            ['Memory Usage', `${data.performance.memoryUsageMb} MB`],
            ['Active Connections', `${data.performance.activeConnections}`],
            ['Total Items Migrated', `${data.performance.totalItemsMigrated}`],
            ['Failed Items', `${data.performance.failedItems}`],
          ],
          theme: 'striped',
          headStyles: { fillColor: [59, 130, 246] } // blue-500
        });
      }

      if (reportType === 'SECURITY_AUDIT' || reportType === 'COMPLIANCE_SNAPSHOT') {
        const finalY = (doc as any).lastAutoTable ? (doc as any).lastAutoTable.finalY : 75;
        const startY = finalY + 15;
        
        doc.setFontSize(14);
        doc.setTextColor(15, 23, 42);
        doc.text('Security & Access Audit', 14, startY);

        autoTable(doc, {
          startY: startY + 5,
          head: [['Security Check', 'Status / Count']],
          body: [
            ['Failed Login Attempts', `${data.security.failedLoginAttempts}`],
            ['Unauthorized Access Blocks', `${data.security.unauthorizedAccessBlocks}`],
            ['Encryption Status', data.security.encryptionStatus],
            ['Active Authentication Tokens', `${data.security.activeTokens}`],
          ],
          theme: 'striped',
          headStyles: { fillColor: [16, 185, 129] } // emerald-500
        });
      }

      doc.save(`${fileName}.pdf`);
    }

    // Add to recent reports
    const newReport: GeneratedReport = {
      id: `REP-${Math.floor(Math.random() * 1000).toString().padStart(3, '0')}`,
      name: `${reportType.replace('_', ' ')} Summary`,
      type: reportType,
      format: exportFormat,
      timestamp: new Date().toISOString(),
      size: exportFormat === 'JSON' ? '45 KB' : '1.2 MB'
    };
    setRecentReports(prev => [newReport, ...prev].slice(0, 5));
    
    setIsGenerating(false);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-slate-900 dark:text-white tracking-tight">Report Generation Engine</h2>
        <p className="text-slate-500 dark:text-slate-400 mt-1">Export summarized performance metrics and security audit summaries for compliance.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Configuration Panel */}
        <div className="lg:col-span-2 bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-xl overflow-hidden">
          <div className="border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/40 p-4 flex items-center space-x-3">
            <Settings className="h-5 w-5 text-blue-400" />
            <h3 className="font-semibold text-slate-100">Report Configuration</h3>
          </div>
          
          <div className="p-6 space-y-8">
            {/* Report Type */}
            <div className="space-y-3">
              <label className="text-sm font-medium text-slate-600 dark:text-slate-300">Report Type</label>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                <button
                  onClick={() => setReportType('PERFORMANCE')}
                  className={`flex flex-col p-4 rounded-lg border-2 text-left transition-all ${
                    reportType === 'PERFORMANCE' 
                      ? 'border-blue-500 bg-blue-900/20' 
                      : 'border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/40 hover:border-slate-600'
                  }`}
                >
                  <Activity className={`h-6 w-6 mb-3 ${reportType === 'PERFORMANCE' ? 'text-blue-400' : 'text-slate-500'}`} />
                  <span className={`font-semibold text-sm ${reportType === 'PERFORMANCE' ? 'text-blue-100' : 'text-slate-600 dark:text-slate-300'}`}>Performance</span>
                  <span className="text-xs text-slate-500 mt-1">Throughput & resource metrics</span>
                </button>
                <button
                  onClick={() => setReportType('SECURITY_AUDIT')}
                  className={`flex flex-col p-4 rounded-lg border-2 text-left transition-all ${
                    reportType === 'SECURITY_AUDIT' 
                      ? 'border-emerald-500 bg-emerald-900/20' 
                      : 'border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/40 hover:border-slate-600'
                  }`}
                >
                  <ShieldAlert className={`h-6 w-6 mb-3 ${reportType === 'SECURITY_AUDIT' ? 'text-emerald-400' : 'text-slate-500'}`} />
                  <span className={`font-semibold text-sm ${reportType === 'SECURITY_AUDIT' ? 'text-emerald-100' : 'text-slate-600 dark:text-slate-300'}`}>Security Audit</span>
                  <span className="text-xs text-slate-500 mt-1">Access logs & encryption status</span>
                </button>
                <button
                  onClick={() => setReportType('COMPLIANCE_SNAPSHOT')}
                  className={`flex flex-col p-4 rounded-lg border-2 text-left transition-all ${
                    reportType === 'COMPLIANCE_SNAPSHOT' 
                      ? 'border-purple-500 bg-purple-900/20' 
                      : 'border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/40 hover:border-slate-600'
                  }`}
                >
                  <FileText className={`h-6 w-6 mb-3 ${reportType === 'COMPLIANCE_SNAPSHOT' ? 'text-purple-400' : 'text-slate-500'}`} />
                  <span className={`font-semibold text-sm ${reportType === 'COMPLIANCE_SNAPSHOT' ? 'text-purple-100' : 'text-slate-600 dark:text-slate-300'}`}>Full Snapshot</span>
                  <span className="text-xs text-slate-500 mt-1">Combined compliance report</span>
                </button>
              </div>
            </div>

            {/* Date Range & Format */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-3">
                <label className="text-sm font-medium text-slate-600 dark:text-slate-300 flex items-center">
                  <Calendar className="h-4 w-4 mr-2 text-slate-500 dark:text-slate-400" />
                  Time Range
                </label>
                <div className="flex bg-slate-50 dark:bg-slate-900/60 p-1 rounded-lg border border-slate-200 dark:border-slate-700">
                  {['24H', '7D', '30D'].map((range) => (
                    <button
                      key={range}
                      onClick={() => setDateRange(range as DateRange)}
                      className={`flex-1 py-2 text-sm font-medium rounded-md transition-all ${
                        dateRange === range
                          ? 'bg-slate-100 dark:bg-slate-700 text-white shadow-sm'
                          : 'text-slate-500 dark:text-slate-400 hover:text-slate-200'
                      }`}
                    >
                      Last {range}
                    </button>
                  ))}
                </div>
              </div>

              <div className="space-y-3">
                <label className="text-sm font-medium text-slate-600 dark:text-slate-300 flex items-center">
                  <Download className="h-4 w-4 mr-2 text-slate-500 dark:text-slate-400" />
                  Export Format
                </label>
                <div className="flex space-x-3">
                  <button
                    onClick={() => setExportFormat('PDF')}
                    className={`flex-1 flex items-center justify-center space-x-2 py-2.5 rounded-lg border transition-all ${
                      exportFormat === 'PDF'
                        ? 'border-red-500/50 bg-red-500/10 text-red-200'
                        : 'border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/40 text-slate-500 dark:text-slate-400 hover:bg-white dark:bg-slate-800'
                    }`}
                  >
                    <FileText className="h-4 w-4" />
                    <span className="font-medium text-sm">PDF Document</span>
                  </button>
                  <button
                    onClick={() => setExportFormat('JSON')}
                    className={`flex-1 flex items-center justify-center space-x-2 py-2.5 rounded-lg border transition-all ${
                      exportFormat === 'JSON'
                        ? 'border-yellow-500/50 bg-yellow-500/10 text-yellow-200'
                        : 'border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/40 text-slate-500 dark:text-slate-400 hover:bg-white dark:bg-slate-800'
                    }`}
                  >
                    <FileJson className="h-4 w-4" />
                    <span className="font-medium text-sm">Structured JSON</span>
                  </button>
                </div>
              </div>
            </div>
            
            {/* Action Bar */}
            <div className="pt-4 mt-6 border-t border-slate-200 dark:border-slate-700 flex justify-end">
              <button
                onClick={handleGenerateReport}
                disabled={isGenerating || (currentRole !== 'GLOBAL_ADMIN' && currentRole !== 'AUDITOR')}
                className={`flex items-center space-x-2 px-6 py-2.5 rounded-lg font-semibold transition-all ${
                  isGenerating
                    ? 'bg-blue-600/50 text-blue-200 cursor-not-allowed'
                    : currentRole !== 'GLOBAL_ADMIN' && currentRole !== 'AUDITOR'
                    ? 'bg-slate-100 dark:bg-slate-700 text-slate-500 dark:text-slate-400 cursor-not-allowed'
                    : 'bg-blue-600 hover:bg-blue-500 text-white shadow-lg shadow-blue-500/20'
                }`}
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="h-5 w-5 animate-spin" />
                    <span>Compiling Data...</span>
                  </>
                ) : (
                  <>
                    <Download className="h-5 w-5" />
                    <span>Generate & Export</span>
                  </>
                )}
              </button>
            </div>
            {currentRole === 'MIGRATION_OPERATOR' && (
              <p className="text-right text-xs text-amber-500 mt-2 flex items-center justify-end">
                <ShieldAlert className="h-3 w-3 mr-1" />
                Insufficient permissions to generate compliance reports. (Requires GLOBAL_ADMIN or AUDITOR).
              </p>
            )}
          </div>
        </div>

        {/* Recent Reports Sidebar */}
        <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-xl overflow-hidden flex flex-col">
          <div className="border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/40 p-4 flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <History className="h-5 w-5 text-emerald-400" />
              <h3 className="font-semibold text-slate-100">Recent Reports</h3>
            </div>
          </div>
          <div className="p-4 flex-1 overflow-y-auto space-y-3">
            {recentReports.length === 0 ? (
              <div className="h-full flex flex-col items-center justify-center text-slate-500 pb-10">
                <FileText className="h-10 w-10 mb-3 opacity-20" />
                <p className="text-sm">No reports generated yet.</p>
              </div>
            ) : (
              recentReports.map(report => (
                <div key={report.id} className="bg-slate-50/50 dark:bg-slate-900/50 border border-slate-200 dark:border-slate-700 rounded-lg p-3 hover:bg-slate-100 dark:bg-slate-700/50 transition-colors group cursor-pointer">
                  <div className="flex items-start justify-between">
                    <div className="flex items-start space-x-3">
                      <div className={`p-2 rounded-md ${report.format === 'PDF' ? 'bg-red-500/10 text-red-400' : 'bg-yellow-500/10 text-yellow-400'}`}>
                        {report.format === 'PDF' ? <FileText className="h-4 w-4" /> : <FileJson className="h-4 w-4" />}
                      </div>
                      <div>
                        <h4 className="text-sm font-medium text-slate-200">{report.name}</h4>
                        <div className="flex items-center space-x-2 mt-1">
                          <span className="text-[10px] bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 px-1.5 py-0.5 rounded font-mono">
                            {report.id}
                          </span>
                          <span className="text-xs text-slate-500">{report.size}</span>
                        </div>
                        <p className="text-xs text-slate-500 mt-1">
                          {new Date(report.timestamp).toLocaleString()}
                        </p>
                      </div>
                    </div>
                    <button className="text-slate-500 hover:text-blue-400 p-1 opacity-0 group-hover:opacity-100 transition-opacity">
                      <Download className="h-4 w-4" />
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
